/**
 * Breakpoint fixture corpus builder. One scenario definition feeds BOTH
 * consumers (the plan's shared corpus):
 *
 *  1. `tests/replay-fixtures/<scenario>/` — the keyless llm-replay A/B
 *     (mechanism verification, plan §5.5):
 *      - `session.jsonl` — the breakpoint snapshot prefix: a session header
 *        plus the `assistant/chunk` events of ONE recorded model step (the
 *        failing tool-call round); llm-replay derives its script from it.
 *      - `replay.override.json` — the scripted A/B arms: a bare
 *        `ReplayEntry[]` replacement carrying the full post-break script
 *        (retry step + ack). A bare array is required because the
 *        `{ patches }` form can append at most ONE entry past the derived
 *        script (llm-replay validates every patch against the ORIGINAL
 *        derived length), while the retry needs two steps after the
 *        breakpoint. Both arms consume the same files; only the cordis
 *        composition differs (plugin mounted or not). The failure itself
 *        comes from the real tool body (schema-valid args the body rejects).
 *
 *  2. `tests/eval-fixtures/<scenario>/session-prefix.jsonl` — the resumable
 *     breakpoint snapshot the real-model eval (plan §6) resumes from: the
 *     full pre-break history (task message, the assistant tool-call block,
 *     the raw `tool/call`, the failed `tool/result`, a completed step). The
 *     ON arm extends the prefix with the recorded failure notice; the eval
 *     runner pre-seeds the plugin's checkpoint store from the fixture so the
 *     resumed session replays the plugin's restart contract verbatim.
 *
 * Fixtures are committed data (never regenerated by the gate at run time);
 * `pnpm build:fixtures` regenerates them and `pnpm check` asserts
 * regeneration is idempotent (byte-identical output).
 *
 * The PTC retry program embeds the `__CHECKPOINT_DIR__` token — the live
 * session's checkpoint directory is machine-specific (os.tmpdir()), so the
 * verification/eval drivers patch the token into the real path at load time.
 */

import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)))
const FIXTURES = join(ROOT, 'packages', 'dsh-tool-retry', 'tests', 'replay-fixtures')
const EVAL_FIXTURES = join(ROOT, 'packages', 'dsh-tool-retry', 'tests', 'eval-fixtures')

interface StreamChunkLike {
  type: string
  [key: string]: unknown
}

/** One model step: the ordered chunk stream the recorded call produced. */
interface ModelStep {
  turn: number
  step: number
  chunks: StreamChunkLike[]
}

/** Tool-call block chunks (the model's call to one tool in one step). */
function toolCallBlock(index: number, callId: string, name: string, args: unknown): StreamChunkLike[] {
  const json = JSON.stringify(args)
  return [
    { type: 'block-start', index, blockType: 'tool-call' },
    { type: 'tool-call-delta', index, id: callId, name, argumentsDelta: json.slice(0, 12) },
    { type: 'tool-call-delta', index, id: callId, name, argumentsDelta: json.slice(12) },
    { type: 'block-end', index, block: { type: 'tool-call', id: callId, name, arguments: json } },
  ]
}

/** Text block chunks (plain acknowledgment text). */
function textBlock(index: number, text: string): StreamChunkLike[] {
  return [
    { type: 'block-start', index, blockType: 'text' },
    { type: 'text-delta', index, text },
    { type: 'block-end', index, block: { type: 'text', text } },
  ]
}

/** Finish a step's chunk stream with usage + the stream terminator. */
function stepChunks(turn: number, step: number, blocks: StreamChunkLike[], reason: 'tool-calls' | 'stop'): ModelStep {
  return {
    turn,
    step,
    chunks: [
      ...blocks,
      { type: 'usage', usage: { inputTokens: 100, outputTokens: blocks.length * 50 } },
      { type: 'finish', reason: { kind: reason } },
    ],
  }
}

/** Serialize steps into a recorded session JSONL (header + chunk events). */
function sessionLog(id: string, createdAt: number, steps: ModelStep[]): string {
  const lines = [JSON.stringify({
    type: 'session', version: 0, id, createdAt, cwd: '/workspace', delegationDepth: 0,
  })]
  let seq = 0
  let time = createdAt
  for (const step of steps) {
    for (const chunk of step.chunks) {
      time += 1
      lines.push(JSON.stringify({
        type: 'assistant/chunk', seq: seq++, time, data: { turn: step.turn, step: step.step, chunk },
      }))
    }
  }
  return `${lines.join('\n')}\n`
}

/** One post-break scripted step as an override entry. */
function scriptEntry(step: ModelStep): { kind: 'chunks'; chunks: StreamChunkLike[] } {
  return { kind: 'chunks', chunks: step.chunks }
}

/** The long failing configuration both native scenarios deploy with. */
function deployArgs(label: string): object {
  return {
    config: {
      kind: 'invalid',
      label,
      replicas: 3,
      region: 'cn-east-1',
      image: 'registry.example.com/app:2026.08.01-rc7',
      env: {
        LOG_LEVEL: 'debug', FEATURE_FLAGS: { retry: true, tracing: true, canary: false },
      },
      resources: { cpu: '2', memory: '4Gi', gpu: null },
      // The payload that makes regeneration expensive — a large embedded
      // template the model would otherwise have to re-emit verbatim.
      template:
        'kind: Deployment\napiVersion: apps/v1\nmetadata:\n  name: {name}\n'
        + 'spec:\n  replicas: {replicas}\n  selector:\n    matchLabels:\n'
        + '      app: {name}\n  template:\n    metadata:\n      labels:\n'
        + '        app: {name}\n    spec:\n      containers:\n      - name: app\n'
        + '        image: {image}\n        ports:\n        - containerPort: 8080\n'
        + '        env:\n        - name: LOG_LEVEL\n          value: "{loglevel}"\n'
        + '        resources:\n          limits:\n            cpu: "2"\n            memory: "4Gi"\n'
        + '          requests:\n            cpu: "500m"\n            memory: "512Mi"\n'
        + '      restartPolicy: Always\n',
    },
  }
}

/** The PTC breakpoint program: an uncaught failure on the marker value. */
const PTC_ORIGINAL = [
  '// RETRY-TARGET',
  'return await tools.boom({ value: "v1-marker" })',
].join('\n')

/** The PTC retry program: read the previous checkpoint, parse, replace, run. */
const PTC_RETRY = [
  '// RETRY-GUARD',
  'const text = (await tools.read({ file_path: "__CHECKPOINT_DIR__/previous/1.json" }))',
  '  .lines.map(line => line.text).join("\\n")',
  'const prev = JSON.parse(text)',
  'if (prev.code.includes("RETRY-GUARD")) return { selfRead: true }',
  'const AsyncFunction = (async () => {}).constructor',
  'const fixed = prev.code.replace("v1-" + "marker", "v2-good")',
  'return await new AsyncFunction("tools", "console", "\'use strict\';\\n" + fixed)(tools, console)',
].join('\n')

interface Scenario {
  name: string
  createdAt: number
  /** The breakpoint round (recorded in session.jsonl). */
  breakpoint: ModelStep
  /** Post-break scripted steps (override patches, appended after the derived entry). */
  retry: ModelStep[]
}

const SCENARIOS: Scenario[] = [
  {
    name: 'native-long-args',
    createdAt: 1,
    breakpoint: stepChunks(1, 1, toolCallBlock(0, 'deploy_1', 'deploy', deployArgs('payments')), 'tool-calls'),
    retry: [
      stepChunks(1, 2, toolCallBlock(0, 'edit_1', 'editPreviousToolCalling', {
        previous_ordinal: 1,
        old_string: '"kind":"invalid"',
        new_string: '"kind":"valid"',
      }), 'tool-calls'),
      stepChunks(1, 3, textBlock(0, 'fixed'), 'stop'),
    ],
  },
  {
    name: 'native-parallel',
    createdAt: 2,
    breakpoint: stepChunks(1, 1, [
      ...toolCallBlock(0, 'deploy_1', 'deploy', deployArgs('billing')),
      ...toolCallBlock(1, 'deploy_2', 'deploy', deployArgs('ledger')),
    ], 'tool-calls'),
    retry: [
      stepChunks(1, 2, [
        ...toolCallBlock(0, 'edit_1', 'editPreviousToolCalling', {
          previous_ordinal: 1,
          old_string: '"kind":"invalid"',
          new_string: '"kind":"valid"',
        }),
        ...toolCallBlock(1, 'edit_2', 'editPreviousToolCalling', {
          call_id: 'deploy_2',
          old_string: '"kind":"invalid"',
          new_string: '"kind":"valid"',
        }),
      ], 'tool-calls'),
      stepChunks(1, 3, textBlock(0, 'done'), 'stop'),
    ],
  },
  {
    name: 'ptc-run-code',
    createdAt: 3,
    breakpoint: stepChunks(1, 1, toolCallBlock(0, 'rc_1', 'run_code', {
      code: PTC_ORIGINAL,
      description: 'run the failing program',
    }), 'tool-calls'),
    retry: [
      stepChunks(1, 2, toolCallBlock(0, 'rc_2', 'run_code', {
        code: PTC_RETRY,
        description: 'retry with a small correction',
      }), 'tool-calls'),
      stepChunks(1, 3, textBlock(0, 'fixed'), 'stop'),
    ],
  },
]

export function buildReplayFixtures(root = FIXTURES): string[] {
  const written: string[] = []
  for (const scenario of SCENARIOS) {
    const dir = join(root, scenario.name)
    mkdirSync(dir, { recursive: true })
    const jsonl = sessionLog(scenario.name, scenario.createdAt, [scenario.breakpoint])
    writeFileSync(join(dir, 'session.jsonl'), jsonl)
    written.push(join(dir, 'session.jsonl'))
    // Bare-array replacement script: the breakpoint round followed by the
    // post-break steps (see the module doc for why not { patches }).
    const override = [scriptEntry(scenario.breakpoint), ...scenario.retry.map(scriptEntry)]
    writeFileSync(join(dir, 'replay.override.json'), `${JSON.stringify(override, null, 2)}\n`)
    written.push(join(dir, 'replay.override.json'))
  }
  return written
}

/* ------------------------------------------------------------------ */
/* §6 eval corpus: resumable breakpoint prefixes                        */
/* ------------------------------------------------------------------ */

/** One failing tool-call block of the breakpoint round. */
interface EvalBlock {
  callId: string
  tool: string
  /** The raw argument string byte-identical to what the model sent. */
  rawArguments: string
  /** The recorded failure text the tool/result carries. */
  errorText: string
  /** The ON-arm notice for this block (the `__CHECKPOINT_DIR__` token is
   * patched by the driver at load time). */
  notice: string
}

/** The tool family one scenario's runner composition must mount. */
type EvalKind = 'deploy' | 'boom' | 'fs' | 'plan'

/** Post-run workspace-state checks (behavioral retry-success evidence). */
interface EvalSuccessCheck {
  kind: 'fileExists' | 'fileContains'
  path: string
  fragment?: string
}

/** One resumable breakpoint snapshot (plan §6 scenario). */
interface EvalScenario {
  name: string
  createdAt: number
  mode: 'native' | 'code'
  kind: EvalKind
  /** Human-readable scenario title (report-facing). */
  title: string
  /** What the breakpoint feed is (input) and what the retry must achieve. */
  description: { input: string; expected: string }
  /** The breakpoint round's failing blocks, in model order. */
  blocks: EvalBlock[]
  /** The original user task (prefix history). */
  task: string
  /** The mode-neutral continuation instruction the eval feeds post-break. */
  continuation: string
  /** Workspace files pre-created before resume (fs scenarios). */
  workspaceFiles?: { path: string; content: string }[]
  /** Post-run workspace-state checks that prove the retry succeeded. */
  successChecks?: EvalSuccessCheck[]
}

/** The long text both fs-tool blocks carry (the regeneration cost). */
const LONG_BODY = [
  '# 迁移与回滚指南',
  '',
  '本节说明缓存层的迁移顺序与回滚路径，内容较长，修改时请保持完整性：',
  '1. 迁移前置：冻结旧接口的写入开关 feature.legacy-write，灰度比例 0%。',
  '2. 双写阶段：新写入同时落旧存储与缓存层，读路径仍走旧存储，持续 3 个观察窗口。',
  '3. 切换阶段：读路径切到缓存层，旧存储保留为冷备，回滚开关 feature.read-fallback 保持开启。',
  '4. 收敛阶段：关闭双写，旧存储进入只读归档；回滚时按 3→2→1 逆序执行。',
  '关键指标：命中率 ≥ 95%，p99 延迟 ≤ 12ms，错误率增幅 ≤ 0.1%。',
  '负责人：平台组值班同学；演练窗口：每周四 02:00-04:00。',
  '回滚预案：任一步骤触发 SLO 告警即冻结灰度并执行逆序回退，回退预计 5 分钟内完成。',
].join('\n')

/** The current on-disk notes.md (version B) — the breakpoint edit's stale
 * old_string predates it. */
const NOTES_V2 = [
  '// notes.md — 当前版本（v2）',
  '// v2: 开头段落已改为新的格式说明，下方正文保持不变。',
  '',
  LONG_BODY,
  '',
  '// 附录：本文件由评测场景自动生成，供长文本 edit 重试使用。',
].join('\n')

/** A fragment of v1 the breakpoint edit still references — v2 dropped it,
 * so the live file no longer contains it (the failure premise). */
const NOTES_STALE_FRAGMENT = '// notes.md — 初始版本（v1）'

/** The long replacement text the breakpoint edit wanted to insert. */
const LONG_NEW_STRING = [
  '缓存层迁移手册（修订版）',
  '',
  '本手册描述缓存层迁移的完整流程，补充了如下内容：',
  '- 迁移前的容量评估与压测基线（基线 p99 与吞吐记录表）；',
  '- 双写阶段的数据一致性校验（对账任务 cron 与偏差告警阈值）；',
  '- 切换阶段的灰度策略与自动熔断规则；',
  '- 收敛阶段后的归档保留期（180 天）与审计要求。',
  '其余章节与旧版一致，见正文。',
].join('\n')

/** The long implementation plan the exit_plan_mode block presents. */
const LONG_PLAN = [
  '# 缓存改造实施计划',
  '',
  '## 1. 背景与目标',
  '为读多写少的核心查询路径引入独立缓存层，目标：命中率 ≥ 95%，p99 延迟下降 40%。',
  '',
  '## 2. 实施方案',
  '直接改造现有模块：在 service 层内联缓存读写，沿用现有连接池，改动范围集中在 3 个文件。',
  '',
  '## 3. 灰度与验收',
  '灰度 1% → 10% → 100%，每档观察 1 天；验收标准：SLO 无回退、命中率达标。',
  '',
  '## 4. 风险与回滚',
  '风险：连接池争用；回滚：关闭开关即回退到直连。',
  '',
  '## 5. 监控与告警',
  '新增命中率、p99 延迟、错误率三块看板，阈值告警接入值班。',
].join('\n')

const PLAN_REJECTION_FEEDBACK = [
  'exit_plan_mode rejected — user feedback:',
  '第 2 节不要直接改造现有模块，改为新增独立缓存层服务；',
  '删除第 5 节「监控与告警」，其余保留。',
].join('\n')

/** The long native config WITHOUT the required `kind` field (INVALID_ARGS). */
function deployArgsMissingKind(label: string): object {
  const args = deployArgs(label) as { config: Record<string, unknown> }
  delete args.config['kind']
  return args
}

/** A truncated (invalid) JSON argument string for the invalid-JSON scenario. */
const BROKEN_DEPLOY_JSON = '{"config": {"kind": "valid", "label": "payments", "replicas": 3, "template": "kind: Deployment\\n"'

const nativeNotice = (callId: string): string => [
  "Your failed call's arguments were saved.",
  `- call id: ${callId}`,
  'To apply a small fix and re-run the call, use `editPreviousToolCalling`',
  `(with call_id "${callId}" — it stays valid).`,
].join('\n')

const EVAL_SCENARIOS: EvalScenario[] = [
  {
    name: 'native-invalid-args',
    createdAt: 11,
    title: '长参数部署：缺失必填字段',
    description: {
      input: '模型要部署一个带长模板的 payments 配置，但漏掉了必填字段 config.kind，schema 校验失败（INVALID_ARGS）。',
      expected: '以最小改动补上 kind 字段并重试成功（deploy 以合法输入重跑）。',
    },
    mode: 'native',
    kind: 'deploy',
    blocks: [{
      callId: 'break_1',
      tool: 'deploy',
      rawArguments: JSON.stringify(deployArgsMissingKind('payments')),
      errorText: 'invalid arguments for deploy: required field config.kind is missing',
      notice: nativeNotice('break_1'),
    }],
    task: 'Deploy the payments service with a long configuration (you forgot the config.kind field).',
    continuation: 'That deploy call failed. Retry it with the smallest possible change and report the outcome.',
  },
  {
    name: 'native-invalid-json',
    createdAt: 12,
    title: '非法 JSON 参数',
    description: {
      input: '模型发出的工具参数字符串不是合法 JSON（截断），调用直接失败。',
      expected: '修复 JSON 文本并重试成功。',
    },
    mode: 'native',
    kind: 'deploy',
    blocks: [{
      callId: 'break_2',
      tool: 'deploy',
      rawArguments: BROKEN_DEPLOY_JSON,
      errorText: 'tool call arguments are not valid JSON: unexpected end of input',
      notice: nativeNotice('break_2'),
    }],
    task: 'Deploy the payments service with a long configuration.',
    continuation: 'That deploy call failed. Retry it with the smallest possible change and report the outcome.',
  },
  {
    name: 'ptc-program-error',
    createdAt: 13,
    title: 'PTC：程序未捕获异常',
    description: {
      input: 'run_code 程序调用 tools.boom（标记值 v1-marker）且未捕获异常，程序整体失败。',
      expected: '修正后的程序无 error 完成（plan §6 判据）。',
    },
    mode: 'code',
    kind: 'boom',
    blocks: [{
      callId: 'break_rc',
      tool: 'run_code',
      rawArguments: JSON.stringify({ code: PTC_ORIGINAL, description: 'run the failing program' }),
      errorText: 'code run failed (exception): boom failed on v1-marker',
      notice: [
        'Your failed `run_code` program was saved.',
        '- path: __CHECKPOINT_DIR__/by-id/break_rc.json',
        'To apply a small fix, read and JSON.parse it in a new `run_code`',
        'program, replace the fragment, and run the corrected program with the',
        'AsyncFunction constructor.',
      ].join('\n'),
    }],
    task: 'Write one run_code program that calls tools.boom({ value: "v1-marker" }) and returns its value.',
    continuation: 'That program failed. Fix it with the smallest change, run the corrected program, and report the result.',
  },
  {
    name: 'native-boom-error',
    createdAt: 16,
    title: '普通模式：标记值工具失败',
    description: {
      input: 'boom 工具在 value 为标记值 v1-marker 时抛错。',
      expected: '换一个合法值重试成功。',
    },
    mode: 'native',
    kind: 'boom',
    blocks: [{
      callId: 'break_boom',
      tool: 'boom',
      rawArguments: JSON.stringify({ value: 'v1-marker' }),
      errorText: 'boom failed on v1-marker',
      notice: nativeNotice('break_boom'),
    }],
    task: 'Call the boom tool with value "v1-marker" and return its result.',
    continuation: 'That call failed. Retry it with the smallest possible change and report the outcome.',
  },
  {
    name: 'ptc-long-fs-edit',
    createdAt: 17,
    title: 'PTC：程序内 edit 失配',
    description: {
      input: 'run_code 程序内 tools.edit 的 old_string 引用了已删除的 v1 片段，程序失败。',
      expected: '修正后的程序完成，且 notes.md 包含新手册片段。',
    },
    mode: 'code',
    kind: 'fs',
    blocks: [{
      callId: 'break_fs_rc',
      tool: 'run_code',
      rawArguments: JSON.stringify({
        code: [
          '// RETRY-TARGET',
          'return await tools.edit({',
          '  file_path: "notes.md",',
          `  old_string: "${NOTES_STALE_FRAGMENT}",`,
          '  new_string: LONG_HANDBOOK,',
          '})',
        ].join('\n').replace('LONG_HANDBOOK', JSON.stringify(LONG_NEW_STRING)),
        description: 'update notes.md via the edit tool',
      }),
      errorText: 'code run failed (exception): ToolCallError: old_string not found in notes.md (the file has changed)',
      notice: [
        'Your failed `run_code` program was saved.',
        '- path: __CHECKPOINT_DIR__/by-id/break_fs_rc.json',
        'To apply a small fix, read and JSON.parse it in a new `run_code`',
        'program, replace the fragment, and run the corrected program with the',
        'AsyncFunction constructor.',
      ].join('\n'),
    }],
    task: 'Write one run_code program that updates notes.md with the tools.edit call (replace the stale header line with a longer revised handbook) and returns the result.',
    continuation: 'That program failed — the old_string no longer matches the file. Fix it with the smallest change, run the corrected program, and report the result.',
    workspaceFiles: [{ path: 'notes.md', content: NOTES_V2 }],
    successChecks: [
      { kind: 'fileContains', path: 'notes.md', fragment: '缓存层迁移手册（修订版）' },
    ],
  },
  {
    name: 'ptc-plan-rejected',
    createdAt: 18,
    title: 'PTC：程序内提交计划被拒',
    description: {
      input: 'run_code 程序内 tools.exit_plan_mode 提交的计划被用户拒绝，程序失败。',
      expected: '修正后的程序重新提交成功。',
    },
    mode: 'code',
    kind: 'plan',
    blocks: [{
      callId: 'break_plan_rc',
      tool: 'run_code',
      rawArguments: JSON.stringify({
        code: [
          '// RETRY-TARGET',
          `return await tools.exit_plan_mode({ plan: ${JSON.stringify(LONG_PLAN)} })`,
        ].join('\n'),
        description: 'submit the plan for review',
      }),
      errorText: `code run failed (exception): ToolCallError: ${PLAN_REJECTION_FEEDBACK}`,
      notice: [
        'Your failed `run_code` program was saved.',
        '- path: __CHECKPOINT_DIR__/by-id/break_plan_rc.json',
        'To apply a small fix, read and JSON.parse it in a new `run_code`',
        'program, replace the fragment, and run the corrected program with the',
        'AsyncFunction constructor.',
      ].join('\n'),
    }],
    task: 'Write one run_code program that submits the caching-refactor plan for review through tools.exit_plan_mode.',
    continuation: 'Your plan was rejected — the user feedback is in the failure result. Revise the plan with the smallest change and re-submit it through a corrected program, then report the outcome.',
  },
  {
    name: 'native-long-fs-write-edit',
    createdAt: 14,
    title: '长文本双失败：write 缺字段 + edit 失配',
    description: {
      input: '并行两个调用同时失败——write（长内容，缺必填 file_path）与 edit（长 new_string，old_string 引用了已删除的 v1 片段）。',
      expected: '两个调用都以最小改动修复：report.md 生成、notes.md 包含新手册片段。',
    },
    mode: 'native',
    kind: 'fs',
    blocks: [
      {
        callId: 'break_fs_w',
        tool: 'write',
        rawArguments: JSON.stringify({ content: LONG_BODY }),
        errorText: 'invalid arguments for write: required field file_path is missing',
        notice: nativeNotice('break_fs_w'),
      },
      {
        callId: 'break_fs_e',
        tool: 'edit',
        rawArguments: JSON.stringify({
          file_path: 'notes.md',
          old_string: NOTES_STALE_FRAGMENT,
          new_string: LONG_NEW_STRING,
        }),
        errorText: 'edit failed: old_string not found in notes.md (the file has changed)',
        notice: nativeNotice('break_fs_e'),
      },
    ],
    task: 'Update notes.md (replace the migration-guide section with a longer revised handbook) and also write the new handbook to report.md.',
    continuation: "Both tool calls failed (the write lacked a required field; the edit's old_string no longer matches the file). Fix each one with the smallest change and retry, then report the outcome.",
    workspaceFiles: [{ path: 'notes.md', content: NOTES_V2 }],
    successChecks: [
      { kind: 'fileExists', path: 'report.md' },
      { kind: 'fileContains', path: 'notes.md', fragment: '缓存层迁移手册（修订版）' },
    ],
  },
  {
    name: 'native-plan-rejected',
    createdAt: 15,
    title: '计划被用户拒绝',
    description: {
      input: 'exit_plan_mode 提交的长实施计划被用户拒绝，用户反馈随失败结果返回。',
      expected: '按反馈修改计划后重新提交成功。',
    },
    mode: 'native',
    kind: 'plan',
    blocks: [{
      callId: 'break_plan',
      tool: 'exit_plan_mode',
      rawArguments: JSON.stringify({ plan: LONG_PLAN }),
      errorText: PLAN_REJECTION_FEEDBACK,
      notice: nativeNotice('break_plan'),
    }],
    task: 'Write an implementation plan for the caching refactor and submit it for review via exit_plan_mode.',
    continuation: 'Your plan was rejected — the user feedback is in the failure result. Revise the plan accordingly and re-submit it through exit_plan_mode with the smallest change, then report the outcome.',
  },
]

/** Serialize one resumable breakpoint prefix (header + full event history). */
function evalPrefix(scenario: EvalScenario): string {
  const lines: string[] = [JSON.stringify({
    type: 'session', version: 0, id: `${scenario.name}-prefix`, createdAt: scenario.createdAt,
    cwd: '/workspace', delegationDepth: 0,
  })]
  const events: { type: string; data: unknown; surfaceOp: 'append' | undefined }[] = [
    { type: 'turn/start', surfaceOp: undefined, data: { turn: 1 } },
    {
      type: 'user/message',
      data: {
        content: [{ type: 'text', text: scenario.task }],
        source: { kind: 'user' },
        role: 'user',
        id: 'prefix-task-message',
      },
      surfaceOp: 'append',
    },
    { type: 'step/start', surfaceOp: undefined, data: { turn: 1, step: 1 } },
    {
      type: 'assistant/message',
      data: {
        turn: 1,
        step: 1,
        message: {
          role: 'assistant',
          content: scenario.blocks.map(block => ({ type: 'tool-call', id: block.callId, name: block.tool, arguments: block.rawArguments })),
          source: { kind: 'model', provider: 'deepseek-official', model: 'deepseek-v4-flash' },
          id: 'prefix-assistant-message',
        },
        usage: {
          inputTokens: 400,
          outputTokens: scenario.blocks.reduce((sum, block) => sum + block.rawArguments.length, 0),
          cacheReadTokens: 0,
          reasoningTokens: 0,
        },
      },
      surfaceOp: 'append',
    },
    ...scenario.blocks.flatMap((block): { type: string; data: unknown; surfaceOp: 'append' | undefined }[] => [
      { type: 'tool/call', surfaceOp: undefined, data: { turn: 1, step: 1, callId: block.callId, name: block.tool, arguments: block.rawArguments } },
      {
        type: 'tool/result',
        data: {
          turn: 1,
          step: 1,
          message: {
            source: { kind: 'tool', callId: block.callId },
            content: [{
              type: 'tool-result',
              toolCallId: block.callId,
              content: [{ type: 'text', text: block.errorText }],
              isError: true,
            }],
            role: 'user',
            id: `prefix-tool-result-${block.callId}`,
          },
        },
        surfaceOp: 'append' as const,
      },
    ]),
    { type: 'step/end', surfaceOp: undefined, data: { turn: 1, step: 1 } },
  ]
  let seq = 0
  let time = scenario.createdAt
  for (const event of events) {
    time += 1
    lines.push(JSON.stringify({
      type: event.type, seq: seq++, time, data: event.data,
      ...event.surfaceOp === undefined ? {} : { surfaceOp: event.surfaceOp },
    }))
  }
  return `${lines.join('\n')}\n`
}

export function buildEvalFixtures(root = EVAL_FIXTURES): string[] {
  const written: string[] = []
  for (const scenario of EVAL_SCENARIOS) {
    const dir = join(root, scenario.name)
    mkdirSync(dir, { recursive: true })
    // The committed prefix ends at the breakpoint (the OFF-arm baseline).
    // The ON arm's notice user/message is appended by the eval driver at
    // load time (its text carries the machine-specific path token); the
    // notice text itself is committed in scenario.json.
    writeFileSync(join(dir, 'session-prefix.jsonl'), evalPrefix(scenario))
    written.push(join(dir, 'session-prefix.jsonl'))
    writeFileSync(join(dir, 'scenario.json'), `${JSON.stringify({
      name: scenario.name,
      mode: scenario.mode,
      kind: scenario.kind,
      title: scenario.title,
      description: scenario.description,
      blocks: scenario.blocks,
      continuation: scenario.continuation,
      ...scenario.workspaceFiles === undefined ? {} : { workspaceFiles: scenario.workspaceFiles },
      ...scenario.successChecks === undefined ? {} : { successChecks: scenario.successChecks },
    }, null, 2)}\n`)
    written.push(join(dir, 'scenario.json'))
  }
  return written
}

// Direct execution: regenerate the committed fixture corpus.
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const written = [...buildReplayFixtures(), ...buildEvalFixtures()]
  for (const file of written) {
    console.log(`wrote ${file}`)
  }
}
