/**
 * Breakpoint fixture corpus builder for the keyless llm-replay A/B
 * (mechanism verification, plan §5.5) and the shared corpus the real-model
 * eval (plan §6) consumes.
 *
 * Each scenario directory holds:
 *  - `session.jsonl` — the breakpoint snapshot prefix: a session header plus
 *    the `assistant/chunk` events of ONE recorded model step (the failing
 *    tool-call round). This is the shared corpus the real-model eval
 *    (plan §6) resumes from; llm-replay can derive its script from it.
 *  - `replay.override.json` — the scripted A/B arms: a bare `ReplayEntry[]`
 *    replacement carrying the full post-break script (retry step + ack).
 *    A bare array is required because the `{ patches }` form can append at
 *    most ONE entry past the derived script (llm-replay validates every
 *    patch against the ORIGINAL derived length), while the retry needs two
 *    steps after the breakpoint. Both arms consume the same files; only the
 *    cordis composition differs (plugin mounted or not). The failure itself
 *    comes from the real tool body (schema-valid args the body rejects).
 *
 * Fixtures are committed data (never regenerated by the gate at run time);
 * `pnpm build:replay-fixtures` regenerates them and `pnpm check` asserts
 * regeneration is idempotent (byte-identical output).
 *
 * The PTC retry program embeds the `__CHECKPOINT_DIR__` token — the live
 * session's checkpoint directory is machine-specific (os.tmpdir()), so the
 * verification spec patches the token into the real path at load time.
 */

import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)))
const FIXTURES = join(ROOT, 'packages', 'dsh-tool-retry', 'tests', 'replay-fixtures')

interface StreamChunkLike {
  type: string
  [key: string]: unknown
}

/** One model step: the ordered chunk stream the recorded call produced. */
interface ModelStep {
  turn: number
  step: number
  chunks: StreamChunkLike[]
}

/** Tool-call block chunks (the model's call to one tool in one step). */
function toolCallBlock(index: number, callId: string, name: string, args: unknown): StreamChunkLike[] {
  const json = JSON.stringify(args)
  return [
    { type: 'block-start', index, blockType: 'tool-call' },
    { type: 'tool-call-delta', index, id: callId, name, argumentsDelta: json.slice(0, 12) },
    { type: 'tool-call-delta', index, id: callId, name, argumentsDelta: json.slice(12) },
    { type: 'block-end', index, block: { type: 'tool-call', id: callId, name, arguments: json } },
  ]
}

/** Text block chunks (plain acknowledgment text). */
function textBlock(index: number, text: string): StreamChunkLike[] {
  return [
    { type: 'block-start', index, blockType: 'text' },
    { type: 'text-delta', index, text },
    { type: 'block-end', index, block: { type: 'text', text } },
  ]
}

/** Finish a step's chunk stream with usage + the stream terminator. */
function stepChunks(turn: number, step: number, blocks: StreamChunkLike[], reason: 'tool-calls' | 'stop'): ModelStep {
  return {
    turn,
    step,
    chunks: [
      ...blocks,
      { type: 'usage', usage: { inputTokens: 100, outputTokens: blocks.length * 50 } },
      { type: 'finish', reason: { kind: reason } },
    ],
  }
}

/** Serialize steps into a recorded session JSONL (header + chunk events). */
function sessionLog(id: string, createdAt: number, steps: ModelStep[]): string {
  const lines = [JSON.stringify({
    type: 'session', version: 0, id, createdAt, cwd: '/workspace', delegationDepth: 0,
  })]
  let seq = 0
  let time = createdAt
  for (const step of steps) {
    for (const chunk of step.chunks) {
      time += 1
      lines.push(JSON.stringify({
        type: 'assistant/chunk', seq: seq++, time, data: { turn: step.turn, step: step.step, chunk },
      }))
    }
  }
  return `${lines.join('\n')}\n`
}

/** One post-break scripted step as an override entry. */
function scriptEntry(step: ModelStep): { kind: 'chunks'; chunks: StreamChunkLike[] } {
  return { kind: 'chunks', chunks: step.chunks }
}

/** The long failing configuration both native scenarios deploy with. */
function deployArgs(label: string): object {
  return {
    config: {
      kind: 'invalid',
      label,
      replicas: 3,
      region: 'cn-east-1',
      image: 'registry.example.com/app:2026.08.01-rc7',
      env: {
        LOG_LEVEL: 'debug', FEATURE_FLAGS: { retry: true, tracing: true, canary: false },
      },
      resources: { cpu: '2', memory: '4Gi', gpu: null },
      // The payload that makes regeneration expensive — a large embedded
      // template the model would otherwise have to re-emit verbatim.
      template:
        'kind: Deployment\napiVersion: apps/v1\nmetadata:\n  name: {name}\n'
        + 'spec:\n  replicas: {replicas}\n  selector:\n    matchLabels:\n'
        + '      app: {name}\n  template:\n    metadata:\n      labels:\n'
        + '        app: {name}\n    spec:\n      containers:\n      - name: app\n'
        + '        image: {image}\n        ports:\n        - containerPort: 8080\n'
        + '        env:\n        - name: LOG_LEVEL\n          value: "{loglevel}"\n'
        + '        resources:\n          limits:\n            cpu: "2"\n            memory: "4Gi"\n'
        + '          requests:\n            cpu: "500m"\n            memory: "512Mi"\n'
        + '      restartPolicy: Always\n',
    },
  }
}

/** The PTC breakpoint program: an uncaught failure on the marker value. */
const PTC_ORIGINAL = [
  '// RETRY-TARGET',
  'return await tools.boom({ value: "v1-marker" })',
].join('\n')

/** The PTC retry program: read the previous checkpoint, parse, replace, run. */
const PTC_RETRY = [
  '// RETRY-GUARD',
  'const text = (await tools.read({ file_path: "__CHECKPOINT_DIR__/previous/1.json" }))',
  '  .lines.map(line => line.text).join("\\n")',
  'const prev = JSON.parse(text)',
  'if (prev.code.includes("RETRY-GUARD")) return { selfRead: true }',
  'const AsyncFunction = (async () => {}).constructor',
  'const fixed = prev.code.replace("v1-" + "marker", "v2-good")',
  'return await new AsyncFunction("tools", "console", "\'use strict\';\\n" + fixed)(tools, console)',
].join('\n')

interface Scenario {
  name: string
  createdAt: number
  /** The breakpoint round (recorded in session.jsonl). */
  breakpoint: ModelStep
  /** Post-break scripted steps (override patches, appended after the derived entry). */
  retry: ModelStep[]
}

const SCENARIOS: Scenario[] = [
  {
    name: 'native-long-args',
    createdAt: 1,
    breakpoint: stepChunks(1, 1, toolCallBlock(0, 'deploy_1', 'deploy', deployArgs('payments')), 'tool-calls'),
    retry: [
      stepChunks(1, 2, toolCallBlock(0, 'edit_1', 'editPreviousToolCalling', {
        previous_ordinal: 1,
        old_string: '"kind":"invalid"',
        new_string: '"kind":"valid"',
      }), 'tool-calls'),
      stepChunks(1, 3, textBlock(0, 'fixed'), 'stop'),
    ],
  },
  {
    name: 'native-parallel',
    createdAt: 2,
    breakpoint: stepChunks(1, 1, [
      ...toolCallBlock(0, 'deploy_1', 'deploy', deployArgs('billing')),
      ...toolCallBlock(1, 'deploy_2', 'deploy', deployArgs('ledger')),
    ], 'tool-calls'),
    retry: [
      stepChunks(1, 2, [
        ...toolCallBlock(0, 'edit_1', 'editPreviousToolCalling', {
          previous_ordinal: 1,
          old_string: '"kind":"invalid"',
          new_string: '"kind":"valid"',
        }),
        ...toolCallBlock(1, 'edit_2', 'editPreviousToolCalling', {
          call_id: 'deploy_2',
          old_string: '"kind":"invalid"',
          new_string: '"kind":"valid"',
        }),
      ], 'tool-calls'),
      stepChunks(1, 3, textBlock(0, 'done'), 'stop'),
    ],
  },
  {
    name: 'ptc-run-code',
    createdAt: 3,
    breakpoint: stepChunks(1, 1, toolCallBlock(0, 'rc_1', 'run_code', {
      code: PTC_ORIGINAL,
      description: 'run the failing program',
    }), 'tool-calls'),
    retry: [
      stepChunks(1, 2, toolCallBlock(0, 'rc_2', 'run_code', {
        code: PTC_RETRY,
        description: 'retry with a small correction',
      }), 'tool-calls'),
      stepChunks(1, 3, textBlock(0, 'fixed'), 'stop'),
    ],
  },
]

export function buildReplayFixtures(root = FIXTURES): string[] {
  const written: string[] = []
  for (const scenario of SCENARIOS) {
    const dir = join(root, scenario.name)
    mkdirSync(dir, { recursive: true })
    const jsonl = sessionLog(scenario.name, scenario.createdAt, [scenario.breakpoint])
    writeFileSync(join(dir, 'session.jsonl'), jsonl)
    written.push(join(dir, 'session.jsonl'))
    // Bare-array replacement script: the breakpoint round followed by the
    // post-break steps (see the module doc for why not { patches }).
    const override = [scriptEntry(scenario.breakpoint), ...scenario.retry.map(scriptEntry)]
    writeFileSync(join(dir, 'replay.override.json'), `${JSON.stringify(override, null, 2)}\n`)
    written.push(join(dir, 'replay.override.json'))
  }
  return written
}

// Direct execution: regenerate the committed fixture corpus.
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  for (const file of buildReplayFixtures()) {
    console.log(`wrote ${file}`)
  }
}
