/**
 * Breakpoint fixture corpus builder. One scenario definition feeds BOTH
 * consumers (the plan's shared corpus):
 *
 *  1. `tests/replay-fixtures/<scenario>/` — the keyless llm-replay A/B
 *     (mechanism verification, plan §5.5):
 *      - `session.jsonl` — the breakpoint snapshot prefix: a session header
 *        plus the `assistant/chunk` events of ONE recorded model step (the
 *        failing tool-call round); llm-replay derives its script from it.
 *      - `replay.override.json` — the scripted A/B arms: a bare
 *        `ReplayEntry[]` replacement carrying the full post-break script
 *        (retry step + ack). A bare array is required because the
 *        `{ patches }` form can append at most ONE entry past the derived
 *        script (llm-replay validates every patch against the ORIGINAL
 *        derived length), while the retry needs two steps after the
 *        breakpoint. Both arms consume the same files; only the cordis
 *        composition differs (plugin mounted or not). The failure itself
 *        comes from the real tool body (schema-valid args the body rejects).
 *
 *  2. `tests/eval-fixtures/<scenario>/session-prefix.jsonl` — the resumable
 *     breakpoint snapshot the real-model eval (plan §6) resumes from: the
 *     full pre-break history (task message, the assistant tool-call block,
 *     the raw `tool/call`, the failed `tool/result`, a completed step). The
 *     ON arm extends the prefix with the recorded failure notice; the eval
 *     runner pre-seeds the plugin's checkpoint store from the fixture so the
 *     resumed session replays the plugin's restart contract verbatim.
 *
 * Fixtures are committed data (never regenerated by the gate at run time);
 * `pnpm build:fixtures` regenerates them and `pnpm check` asserts
 * regeneration is idempotent (byte-identical output).
 *
 * The PTC retry program embeds the `__CHECKPOINT_DIR__` token — the live
 * session's checkpoint directory is machine-specific (os.tmpdir()), so the
 * verification/eval drivers patch the token into the real path at load time.
 */

import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)))
const FIXTURES = join(ROOT, 'packages', 'dsh-tool-retry', 'tests', 'replay-fixtures')
const EVAL_FIXTURES = join(ROOT, 'packages', 'dsh-tool-retry', 'tests', 'eval-fixtures')

interface StreamChunkLike {
  type: string
  [key: string]: unknown
}

/** One model step: the ordered chunk stream the recorded call produced. */
interface ModelStep {
  turn: number
  step: number
  chunks: StreamChunkLike[]
}

/** Tool-call block chunks (the model's call to one tool in one step). */
function toolCallBlock(index: number, callId: string, name: string, args: unknown): StreamChunkLike[] {
  const json = JSON.stringify(args)
  return [
    { type: 'block-start', index, blockType: 'tool-call' },
    { type: 'tool-call-delta', index, id: callId, name, argumentsDelta: json.slice(0, 12) },
    { type: 'tool-call-delta', index, id: callId, name, argumentsDelta: json.slice(12) },
    { type: 'block-end', index, block: { type: 'tool-call', id: callId, name, arguments: json } },
  ]
}

/** Text block chunks (plain acknowledgment text). */
function textBlock(index: number, text: string): StreamChunkLike[] {
  return [
    { type: 'block-start', index, blockType: 'text' },
    { type: 'text-delta', index, text },
    { type: 'block-end', index, block: { type: 'text', text } },
  ]
}

/** Finish a step's chunk stream with usage + the stream terminator. */
function stepChunks(turn: number, step: number, blocks: StreamChunkLike[], reason: 'tool-calls' | 'stop'): ModelStep {
  return {
    turn,
    step,
    chunks: [
      ...blocks,
      { type: 'usage', usage: { inputTokens: 100, outputTokens: blocks.length * 50 } },
      { type: 'finish', reason: { kind: reason } },
    ],
  }
}

/** Serialize steps into a recorded session JSONL (header + chunk events). */
function sessionLog(id: string, createdAt: number, steps: ModelStep[]): string {
  const lines = [JSON.stringify({
    type: 'session', version: 0, id, createdAt, cwd: '/workspace', delegationDepth: 0,
  })]
  let seq = 0
  let time = createdAt
  for (const step of steps) {
    for (const chunk of step.chunks) {
      time += 1
      lines.push(JSON.stringify({
        type: 'assistant/chunk', seq: seq++, time, data: { turn: step.turn, step: step.step, chunk },
      }))
    }
  }
  return `${lines.join('\n')}\n`
}

/** One post-break scripted step as an override entry. */
function scriptEntry(step: ModelStep): { kind: 'chunks'; chunks: StreamChunkLike[] } {
  return { kind: 'chunks', chunks: step.chunks }
}

/** The long failing configuration both native scenarios deploy with. */
function deployArgs(label: string): object {
  return {
    config: {
      kind: 'invalid',
      label,
      replicas: 3,
      region: 'cn-east-1',
      image: 'registry.example.com/app:2026.08.01-rc7',
      env: {
        LOG_LEVEL: 'debug', FEATURE_FLAGS: { retry: true, tracing: true, canary: false },
      },
      resources: { cpu: '2', memory: '4Gi', gpu: null },
      // The payload that makes regeneration expensive — a large embedded
      // template the model would otherwise have to re-emit verbatim.
      template:
        'kind: Deployment\napiVersion: apps/v1\nmetadata:\n  name: {name}\n'
        + 'spec:\n  replicas: {replicas}\n  selector:\n    matchLabels:\n'
        + '      app: {name}\n  template:\n    metadata:\n      labels:\n'
        + '        app: {name}\n    spec:\n      containers:\n      - name: app\n'
        + '        image: {image}\n        ports:\n        - containerPort: 8080\n'
        + '        env:\n        - name: LOG_LEVEL\n          value: "{loglevel}"\n'
        + '        resources:\n          limits:\n            cpu: "2"\n            memory: "4Gi"\n'
        + '          requests:\n            cpu: "500m"\n            memory: "512Mi"\n'
        + '      restartPolicy: Always\n',
    },
  }
}

/** The PTC breakpoint program: an uncaught failure on the marker value. */
const PTC_ORIGINAL = [
  '// RETRY-TARGET',
  'return await tools.boom({ value: "v1-marker" })',
].join('\n')

/** The PTC retry program: read the previous checkpoint, parse, replace, run. */
const PTC_RETRY = [
  '// RETRY-GUARD',
  'const text = (await tools.read({ file_path: "__CHECKPOINT_DIR__/previous/1.json" }))',
  '  .lines.map(line => line.text).join("\\n")',
  'const prev = JSON.parse(text)',
  'if (prev.code.includes("RETRY-GUARD")) return { selfRead: true }',
  'const AsyncFunction = (async () => {}).constructor',
  'const fixed = prev.code.replace("v1-" + "marker", "v2-good")',
  'return await new AsyncFunction("tools", "console", "\'use strict\';\\n" + fixed)(tools, console)',
].join('\n')

interface Scenario {
  name: string
  createdAt: number
  /** The breakpoint round (recorded in session.jsonl). */
  breakpoint: ModelStep
  /** Post-break scripted steps (override patches, appended after the derived entry). */
  retry: ModelStep[]
}

const SCENARIOS: Scenario[] = [
  {
    name: 'native-long-args',
    createdAt: 1,
    breakpoint: stepChunks(1, 1, toolCallBlock(0, 'deploy_1', 'deploy', deployArgs('payments')), 'tool-calls'),
    retry: [
      stepChunks(1, 2, toolCallBlock(0, 'edit_1', 'editPreviousToolCalling', {
        previous_ordinal: 1,
        old_string: '"kind":"invalid"',
        new_string: '"kind":"valid"',
      }), 'tool-calls'),
      stepChunks(1, 3, textBlock(0, 'fixed'), 'stop'),
    ],
  },
  {
    name: 'native-parallel',
    createdAt: 2,
    breakpoint: stepChunks(1, 1, [
      ...toolCallBlock(0, 'deploy_1', 'deploy', deployArgs('billing')),
      ...toolCallBlock(1, 'deploy_2', 'deploy', deployArgs('ledger')),
    ], 'tool-calls'),
    retry: [
      stepChunks(1, 2, [
        ...toolCallBlock(0, 'edit_1', 'editPreviousToolCalling', {
          previous_ordinal: 1,
          old_string: '"kind":"invalid"',
          new_string: '"kind":"valid"',
        }),
        ...toolCallBlock(1, 'edit_2', 'editPreviousToolCalling', {
          call_id: 'deploy_2',
          old_string: '"kind":"invalid"',
          new_string: '"kind":"valid"',
        }),
      ], 'tool-calls'),
      stepChunks(1, 3, textBlock(0, 'done'), 'stop'),
    ],
  },
  {
    name: 'ptc-run-code',
    createdAt: 3,
    breakpoint: stepChunks(1, 1, toolCallBlock(0, 'rc_1', 'run_code', {
      code: PTC_ORIGINAL,
      description: 'run the failing program',
    }), 'tool-calls'),
    retry: [
      stepChunks(1, 2, toolCallBlock(0, 'rc_2', 'run_code', {
        code: PTC_RETRY,
        description: 'retry with a small correction',
      }), 'tool-calls'),
      stepChunks(1, 3, textBlock(0, 'fixed'), 'stop'),
    ],
  },
]

export function buildReplayFixtures(root = FIXTURES): string[] {
  const written: string[] = []
  for (const scenario of SCENARIOS) {
    const dir = join(root, scenario.name)
    mkdirSync(dir, { recursive: true })
    const jsonl = sessionLog(scenario.name, scenario.createdAt, [scenario.breakpoint])
    writeFileSync(join(dir, 'session.jsonl'), jsonl)
    written.push(join(dir, 'session.jsonl'))
    // Bare-array replacement script: the breakpoint round followed by the
    // post-break steps (see the module doc for why not { patches }).
    const override = [scriptEntry(scenario.breakpoint), ...scenario.retry.map(scriptEntry)]
    writeFileSync(join(dir, 'replay.override.json'), `${JSON.stringify(override, null, 2)}\n`)
    written.push(join(dir, 'replay.override.json'))
  }
  return written
}

/* ------------------------------------------------------------------ */
/* §6 eval corpus: resumable breakpoint prefixes                        */
/* ------------------------------------------------------------------ */

/** One resumable breakpoint snapshot (plan §6 scenario). */
interface EvalScenario {
  name: string
  createdAt: number
  mode: 'native' | 'code'
  /** The breakpoint call identity (the notice and checkpoint store key). */
  callId: string
  tool: string
  /** The raw argument string byte-identical to what the model sent. */
  rawArguments: string
  /** The recorded failure text the tool/result carries. */
  errorText: string
  /** The original user task (prefix history). */
  task: string
  /** The mode-neutral continuation instruction the eval feeds post-break. */
  continuation: string
  /** The ON-arm notice text (recorded at the end of the prefix; the
   * `__CHECKPOINT_DIR__` token is patched by the driver at load time). */
  notice: string
}

/** The long native config WITHOUT the required `kind` field (INVALID_ARGS). */
function deployArgsMissingKind(label: string): object {
  const args = deployArgs(label) as { config: Record<string, unknown> }
  delete args.config['kind']
  return args
}

/** A truncated (invalid) JSON argument string for the invalid-JSON scenario. */
const BROKEN_DEPLOY_JSON = '{"config": {"kind": "valid", "label": "payments", "replicas": 3, "template": "kind: Deployment\\n"'

const EVAL_SCENARIOS: EvalScenario[] = [
  {
    name: 'native-invalid-args',
    createdAt: 11,
    mode: 'native',
    callId: 'break_1',
    tool: 'deploy',
    rawArguments: JSON.stringify(deployArgsMissingKind('payments')),
    errorText: 'invalid arguments for deploy: required field config.kind is missing',
    task: 'Deploy the payments service with a long configuration (you forgot the config.kind field).',
    continuation: 'That deploy call failed. Retry it with the smallest possible change and report the outcome.',
    notice: [
      "Your failed call's arguments were saved.",
      '- call id: break_1',
      'To apply a small fix and re-run the call, use `editPreviousToolCalling`',
      '(with call_id "break_1" — it stays valid).',
    ].join('\n'),
  },
  {
    name: 'native-invalid-json',
    createdAt: 12,
    mode: 'native',
    callId: 'break_2',
    tool: 'deploy',
    rawArguments: BROKEN_DEPLOY_JSON,
    errorText: 'tool call arguments are not valid JSON: unexpected end of input',
    task: 'Deploy the payments service with a long configuration.',
    continuation: 'That deploy call failed. Retry it with the smallest possible change and report the outcome.',
    notice: [
      "Your failed call's arguments were saved.",
      '- call id: break_2',
      'To apply a small fix and re-run the call, use `editPreviousToolCalling`',
      '(with call_id "break_2" — it stays valid).',
    ].join('\n'),
  },
  {
    name: 'ptc-program-error',
    createdAt: 13,
    mode: 'code',
    callId: 'break_rc',
    tool: 'run_code',
    rawArguments: JSON.stringify({ code: PTC_ORIGINAL, description: 'run the failing program' }),
    errorText: 'code run failed (exception): boom failed on v1-marker',
    task: 'Write one run_code program that calls tools.boom({ value: "v1-marker" }) and returns its value.',
    continuation: 'That program failed. Fix it with the smallest change, run the corrected program, and report the result.',
    notice: [
      'Your failed `run_code` program was saved.',
      '- path: __CHECKPOINT_DIR__/by-id/break_rc.json',
      'To apply a small fix, read and JSON.parse it in a new `run_code`',
      'program, replace the fragment, and run the corrected program with the',
      'AsyncFunction constructor.',
    ].join('\n'),
  },
]

/** Serialize one resumable breakpoint prefix (header + full event history). */
function evalPrefix(scenario: EvalScenario): string {
  const lines: string[] = [JSON.stringify({
    type: 'session', version: 0, id: `${scenario.name}-prefix`, createdAt: scenario.createdAt,
    cwd: '/workspace', delegationDepth: 0,
  })]
  const events: { type: string; data: unknown; surfaceOp?: 'append' }[] = [
    { type: 'turn/start', data: { turn: 1 } },
    {
      type: 'user/message',
      data: {
        content: [{ type: 'text', text: scenario.task }],
        source: { kind: 'user' },
        role: 'user',
        id: 'prefix-task-message',
      },
      surfaceOp: 'append',
    },
    { type: 'step/start', data: { turn: 1, step: 1 } },
    {
      type: 'assistant/message',
      data: {
        turn: 1,
        step: 1,
        message: {
          role: 'assistant',
          content: [{ type: 'tool-call', id: scenario.callId, name: scenario.tool, arguments: scenario.rawArguments }],
          source: { kind: 'model', provider: 'deepseek-official', model: 'deepseek-v4-flash' },
          id: 'prefix-assistant-message',
        },
        usage: { inputTokens: 400, outputTokens: scenario.rawArguments.length, cacheReadTokens: 0, reasoningTokens: 0 },
      },
      surfaceOp: 'append',
    },
    { type: 'tool/call', data: { turn: 1, step: 1, callId: scenario.callId, name: scenario.tool, arguments: scenario.rawArguments } },
    {
      type: 'tool/result',
      data: {
        turn: 1,
        step: 1,
        message: {
          source: { kind: 'tool', callId: scenario.callId },
          content: [{
            type: 'tool-result',
            toolCallId: scenario.callId,
            content: [{ type: 'text', text: scenario.errorText }],
            isError: true,
          }],
          role: 'user',
          id: 'prefix-tool-result-message',
        },
      },
      surfaceOp: 'append',
    },
    { type: 'step/end', data: { turn: 1, step: 1 } },
  ]
  let seq = 0
  let time = scenario.createdAt
  for (const event of events) {
    time += 1
    lines.push(JSON.stringify({
      type: event.type, seq: seq++, time, data: event.data,
      ...event.surfaceOp === undefined ? {} : { surfaceOp: event.surfaceOp },
    }))
  }
  return `${lines.join('\n')}\n`
}

export function buildEvalFixtures(root = EVAL_FIXTURES): string[] {
  const written: string[] = []
  for (const scenario of EVAL_SCENARIOS) {
    const dir = join(root, scenario.name)
    mkdirSync(dir, { recursive: true })
    // The committed prefix ends at the breakpoint (the OFF-arm baseline).
    // The ON arm's notice user/message is appended by the eval driver at
    // load time (its text carries the machine-specific path token); the
    // notice text itself is committed in scenario.json.
    writeFileSync(join(dir, 'session-prefix.jsonl'), evalPrefix(scenario))
    written.push(join(dir, 'session-prefix.jsonl'))
    writeFileSync(join(dir, 'scenario.json'), `${JSON.stringify({
      name: scenario.name,
      mode: scenario.mode,
      callId: scenario.callId,
      tool: scenario.tool,
      continuation: scenario.continuation,
      notice: scenario.notice,
    }, null, 2)}\n`)
    written.push(join(dir, 'scenario.json'))
  }
  return written
}

// Direct execution: regenerate the committed fixture corpus.
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const written = [...buildReplayFixtures(), ...buildEvalFixtures()]
  for (const file of written) {
    console.log(`wrote ${file}`)
  }
}
