/**
 * Generate the launch overlay (`cordis.yml`) and the tsdown banner id
 * (`packages/dsh-tool-retry/entry-name.json`) from this checkout's stable
 * development alias.
 *
 * The launchers materialize this alias in the active profile's node_modules
 * as a symlink to the package directory, so the native-ESM Loader resolves
 * the same bare name from that profile anchor. Run with tsx:
 * `tsx scripts/gen-config.ts`.
 */
import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { DEVELOPMENT_ENTRY_NAME } from './development-entry.ts'

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const entry = join(root, 'packages', 'dsh-tool-retry')

if (!existsSync(join(entry, 'package.json'))) {
  console.error(`gen-config: plugin package not found at ${entry}`)
  process.exit(1)
}

const cordisYaml = [
  '# Generated by scripts/gen-config.ts — do not edit by hand.',
  '# The launchers symlink this development-only bare name into the active profile.',
  '- insert:',
  '    - id: tool-retry',
  `      name: ${JSON.stringify(DEVELOPMENT_ENTRY_NAME)}`,
  '',
].join('\n')
writeFileSync(join(root, 'cordis.yml'), cordisYaml)
mkdirSync(entry, { recursive: true })
writeFileSync(join(entry, 'entry-name.json'), `${JSON.stringify({ name: DEVELOPMENT_ENTRY_NAME }, null, 2)}\n`)
console.log(`gen-config: cordis.yml + packages/dsh-tool-retry/entry-name.json -> ${DEVELOPMENT_ENTRY_NAME}`)
